plugins {
    id 'com.android.application'
    id 'kotlin-android'
}

android {
    namespace 'top.eiyooooo.easycontrol.app'
    compileSdk 34

    defaultConfig {
        applicationId 'top.eiyooooo.easycontrol.app'
        minSdk 21
        targetSdk 34
        versionCode 10611
        versionName "1.6.11"
    }

    buildTypes {
        release {
            debuggable false
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    buildFeatures {
        viewBinding true
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    packagingOptions {
        resources.excludes.add("META-INF/*")
    }
}

dependencies {
    implementation 'com.github.MuntashirAkon:libadb-android:3.0.0'
    implementation 'com.github.MuntashirAkon:sun-security-android:1.1'
    implementation 'org.lsposed.hiddenapibypass:hiddenapibypass:4.3'
}